# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
  schedule:
  - cron: "0 0 * * *"
  push: 
    branches: ["master"]

jobs:
  build:
    name: Release Nightly Snapshot
    runs-on: linux-latest
    steps:
      - name: Checkout master Branch
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Create Release
        id: nightly-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'nightly-alpha'
          release_name: 'nightly-build'
          draft: false
          prerelease: true
